export const jobTypes = [
  { label: 'Full-time', value: 'Full-time' },
  { label: 'Remote', value: 'Remote' },
  { label: 'Part-time', value: 'Part-time' },
  { label: 'Freelance', value: 'Freelance' },
  { label: 'Contract', value: 'Contract' },
  { label: 'Temporary', value: 'Temporary' },
  { label: 'Internship', value: 'Internship' },
  { label: 'Flexible Schedule', value: 'Flexible Schedule' },
];

export const cities = [
  { label: 'Mumbai, MH', value: 'Mumbai' },
  { label: 'Delhi, DL', value: 'Delhi' },
  { label: 'Kolkata, WB', value: 'Kolkata' },
  { label: 'Chennai, TN', value: 'Chennai' },
  { label: 'Bangalore, KA', value: 'Bangalore' },
  { label: 'Hyderabad, TG', value: 'Hyderabad' },
  { label: 'Pune, MH', value: 'Pune' },
  { label: 'Ahmedabad, GJ', value: 'Ahmedabad' },
  { label: 'Jaipur, RJ', value: 'Jaipur' },
  { label: 'Lucknow, UP', value: 'Lucknow' },
  { label: 'Surat, GJ', value: 'Surat' },
  { label: 'Kanpur, UP', value: 'Kanpur' },
  { label: 'Nagpur, MH', value: 'Nagpur' },
  { label: 'Visakhapatnam, AP', value: 'Visakhapatnam' },
  { label: 'Indore, MP', value: 'Indore' },
  { label: 'Thane, MH', value: 'Thane' },
  { label: 'Bhopal, MP', value: 'Bhopal' },
  { label: 'Patna, BR', value: 'Patna' },
  { label: 'Vadodara, GJ', value: 'Vadodara' },
  { label: 'Ghaziabad, UP', value: 'Ghaziabad' },
  { label: 'Ludhiana, PB', value: 'Ludhiana' },
  { label: 'Agra, UP', value: 'Agra' },
  { label: 'Nashik, MH', value: 'Nashik' },
  { label: 'Faridabad, HR', value: 'Faridabad' },
  { label: 'Meerut, UP', value: 'Meerut' },
  { label: 'Rajkot, GJ', value: 'Rajkot' },
  { label: 'Varanasi, UP', value: 'Varanasi' },
  { label: 'Srinagar, JK', value: 'Srinagar' },
  { label: 'Aurangabad, MH', value: 'Aurangabad' },
  { label: 'Dhanbad, JH', value: 'Dhanbad' },
  { label: 'Amritsar, PB', value: 'Amritsar' },
  { label: 'Navi Mumbai, MH', value: 'Navi Mumbai' },
  { label: 'Allahabad, UP', value: 'Allahabad' },
  { label: 'Howrah, WB', value: 'Howrah' },
  { label: 'Gwalior, MP', value: 'Gwalior' },
  { label: 'Jabalpur, MP', value: 'Jabalpur' },
  { label: 'Coimbatore, TN', value: 'Coimbatore' },
  { label: 'Vijayawada, AP', value: 'Vijayawada' },
  { label: 'Jodhpur, RJ', value: 'Jodhpur' },
  { label: 'Madurai, TN', value: 'Madurai' },
  { label: 'Raipur, CG', value: 'Raipur' },
  { label: 'Kota, RJ', value: 'Kota' },
  { label: 'Chandigarh, CH', value: 'Chandigarh' },
  { label: 'Guwahati, AS', value: 'Guwahati' },
  { label: 'Solapur, MH', value: 'Solapur' },
  { label: 'Hubli-Dharwad, KA', value: 'Hubli-Dharwad' },
  { label: 'Bareilly, UP', value: 'Bareilly' },
  { label: 'Moradabad, UP', value: 'Moradabad' },
  { label: 'Mysore, KA', value: 'Mysore' },
  { label: 'Gurgaon, HR', value: 'Gurgaon' },
  { label: 'Aligarh, UP', value: 'Aligarh' },
  { label: 'Jalandhar, PB', value: 'Jalandhar' },
  { label: 'Tiruchirappalli, TN', value: 'Tiruchirappalli' },
  { label: 'Bhubaneswar, OD', value: 'Bhubaneswar' },
  { label: 'Salem, TN', value: 'Salem' },
  { label: 'Warangal, TG', value: 'Warangal' },
  { label: 'Guntur, AP', value: 'Guntur' },
  { label: 'Bhiwandi, MH', value: 'Bhiwandi' },
  { label: 'Saharanpur, UP', value: 'Saharanpur' },
  { label: 'Gorakhpur, UP', value: 'Gorakhpur' },
  { label: 'Bikaner, RJ', value: 'Bikaner' },
  { label: 'Amravati, MH', value: 'Amravati' },
  { label: 'Noida, UP', value: 'Noida' },
  { label: 'Jamshedpur, JH', value: 'Jamshedpur' },
  { label: 'Bhilai, CG', value: 'Bhilai' },
  { label: 'Cuttack, OD', value: 'Cuttack' },
  { label: 'Firozabad, UP', value: 'Firozabad' },
  { label: 'Kochi, KL', value: 'Kochi' },
  { label: 'Nellore, AP', value: 'Nellore' },
  { label: 'Bhavnagar, GJ', value: 'Bhavnagar' },
  { label: 'Dehradun, UK', value: 'Dehradun' },
  { label: 'Durgapur, WB', value: 'Durgapur' },
  { label: 'Asansol, WB', value: 'Asansol' },
  { label: 'Rourkela, OD', value: 'Rourkela' },
  { label: 'Nanded, MH', value: 'Nanded' },
  { label: 'Kolhapur, MH', value: 'Kolhapur' },
  { label: 'Ajmer, RJ', value: 'Ajmer' },
  { label: 'Akola, MH', value: 'Akola' },
  { label: 'KA - Gulbarga', value: 'Gulbarga' },
];
